// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: bettor/v1alpha/bettor.proto

package bettorv1alphaconnect

import (
	context "context"
	errors "errors"
	connect_go "github.com/bufbuild/connect-go"
	v1alpha "github.com/elh/bettor/api/bettor/v1alpha"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect_go.IsAtLeastVersion0_1_0

const (
	// BettorServiceName is the fully-qualified name of the BettorService service.
	BettorServiceName = "bettor.v1alpha.BettorService"
)

// BettorServiceClient is a client for the bettor.v1alpha.BettorService service.
type BettorServiceClient interface {
	// CreateUser creates a new user.
	CreateUser(context.Context, *connect_go.Request[v1alpha.CreateUserRequest]) (*connect_go.Response[v1alpha.CreateUserResponse], error)
	// GetUser returns a user by ID.
	GetUser(context.Context, *connect_go.Request[v1alpha.GetUserRequest]) (*connect_go.Response[v1alpha.GetUserResponse], error)
}

// NewBettorServiceClient constructs a client for the bettor.v1alpha.BettorService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewBettorServiceClient(httpClient connect_go.HTTPClient, baseURL string, opts ...connect_go.ClientOption) BettorServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	return &bettorServiceClient{
		createUser: connect_go.NewClient[v1alpha.CreateUserRequest, v1alpha.CreateUserResponse](
			httpClient,
			baseURL+"/bettor.v1alpha.BettorService/CreateUser",
			opts...,
		),
		getUser: connect_go.NewClient[v1alpha.GetUserRequest, v1alpha.GetUserResponse](
			httpClient,
			baseURL+"/bettor.v1alpha.BettorService/GetUser",
			opts...,
		),
	}
}

// bettorServiceClient implements BettorServiceClient.
type bettorServiceClient struct {
	createUser *connect_go.Client[v1alpha.CreateUserRequest, v1alpha.CreateUserResponse]
	getUser    *connect_go.Client[v1alpha.GetUserRequest, v1alpha.GetUserResponse]
}

// CreateUser calls bettor.v1alpha.BettorService.CreateUser.
func (c *bettorServiceClient) CreateUser(ctx context.Context, req *connect_go.Request[v1alpha.CreateUserRequest]) (*connect_go.Response[v1alpha.CreateUserResponse], error) {
	return c.createUser.CallUnary(ctx, req)
}

// GetUser calls bettor.v1alpha.BettorService.GetUser.
func (c *bettorServiceClient) GetUser(ctx context.Context, req *connect_go.Request[v1alpha.GetUserRequest]) (*connect_go.Response[v1alpha.GetUserResponse], error) {
	return c.getUser.CallUnary(ctx, req)
}

// BettorServiceHandler is an implementation of the bettor.v1alpha.BettorService service.
type BettorServiceHandler interface {
	// CreateUser creates a new user.
	CreateUser(context.Context, *connect_go.Request[v1alpha.CreateUserRequest]) (*connect_go.Response[v1alpha.CreateUserResponse], error)
	// GetUser returns a user by ID.
	GetUser(context.Context, *connect_go.Request[v1alpha.GetUserRequest]) (*connect_go.Response[v1alpha.GetUserResponse], error)
}

// NewBettorServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewBettorServiceHandler(svc BettorServiceHandler, opts ...connect_go.HandlerOption) (string, http.Handler) {
	mux := http.NewServeMux()
	mux.Handle("/bettor.v1alpha.BettorService/CreateUser", connect_go.NewUnaryHandler(
		"/bettor.v1alpha.BettorService/CreateUser",
		svc.CreateUser,
		opts...,
	))
	mux.Handle("/bettor.v1alpha.BettorService/GetUser", connect_go.NewUnaryHandler(
		"/bettor.v1alpha.BettorService/GetUser",
		svc.GetUser,
		opts...,
	))
	return "/bettor.v1alpha.BettorService/", mux
}

// UnimplementedBettorServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedBettorServiceHandler struct{}

func (UnimplementedBettorServiceHandler) CreateUser(context.Context, *connect_go.Request[v1alpha.CreateUserRequest]) (*connect_go.Response[v1alpha.CreateUserResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("bettor.v1alpha.BettorService.CreateUser is not implemented"))
}

func (UnimplementedBettorServiceHandler) GetUser(context.Context, *connect_go.Request[v1alpha.GetUserRequest]) (*connect_go.Response[v1alpha.GetUserResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("bettor.v1alpha.BettorService.GetUser is not implemented"))
}
